upstream backend_test { server backend-test:8000; }

server {
    listen 80;
    server_name localhost;
    client_max_body_size 100m;

    location /api/ {
        proxy_pass http://backend_test;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /static/previews/ {
        alias /data/previews/;
    }

    location /data/gifs/ {
        alias /data/gifs/;
    }

    location /data/icons/ {
        alias /data/icons/;
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}
